[package]
name = "sigwa-storages-sqlite"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
sigwa-core = { workspace = true }

async-trait = { workspace = true }

tokio = { workspace = true, features = ["fs"] }
